language: cpp
sudo: true

dist: trusty

git:
  depth: 1

addons:
  apt:
    sources:
      # newer gcc and clang
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
    packages:
      - libz-dev

env:
    - LLVM=3.8 PTA=fs
    - LLVM=3.8 PTA=fi
    - LLVM=4.0 PTA=fs
    - LLVM=4.0 PTA=fi
    - LLVM=5.0 PTA=fs
    - LLVM=5.0 PTA=fi

compiler:
    - 'clang++'
    - 'g++'
    - 'g++-5'

install:
  - git clone --depth 1 https://github.com/tomsik68/travis-llvm.git
  - cd travis-llvm
  - chmod +x travis-llvm.sh
  - ./travis-llvm.sh ${LLVM}
  - cd ..

script:
  - cmake -DCMAKE_BUILD_TYPE=DEBUG .
  - make -j2
  - cd tests
  - make
  - DG_TESTS_PTA="$PTA" make test

notifications:
    email: false
